const pairings = {
  angola: "AGO",
  albania: "ALB",
  "united arab emirates": "ARE",
  armenia: "ARM",
  australia: "AUS",
  austria: "AUT",
  azerbaijan: "AZE",
  burundi: "BDI",
  belgium: "BEL",
  benin: "BEN",
  "burkina faso": "BFA",
  bangladesh: "BGD",
  bulgaria: "BGR",
  "bosnia and herzegovina": "BIH",
  belarus: "BLR",
  belize: "BLZ",
  bolivia: "BOL",
  brazil: "BRA",
  bhutan: "BTN",
  botswana: "BWA",
  "central african republic": "CAF",
  canada: "CAN",
  switzerland: "CHE",
  chile: "CHL",
  china: "CHN",
  "cote d'ivoire": "CIV",
  cameroon: "CMR",
  "congo, dem. rep.": "COD",
  "congo, rep.": "COG",
  colombia: "COL",
  comoros: "COM",
  "cabo verde": "CPV",
  "costa rica": "CRI",
  cyprus: "CYP",
  "czech republic": "CZE",
  germany: "DEU",
  djibouti: "DJI",
  denmark: "DNK",
  "dominican republic": "DOM",
  algeria: "DZA",
  ecuador: "ECU",
  "egypt, arab rep.": "EGY",
  spain: "ESP",
  estonia: "EST",
  ethiopia: "ETH",
  finland: "FIN",
  fiji: "FJI",
  france: "FRA",
  "micronesia, fed. sts.": "FSM",
  gabon: "GAB",
  "united kingdom": "GBR",
  georgia: "GEO",
  ghana: "GHA",
  guinea: "GIN",
  "gambia, the": "GMB",
  "guinea-bissau": "GNB",
  greece: "GRC",
  guatemala: "GTM",
  guyana: "GUY",
  honduras: "HND",
  croatia: "HRV",
  haiti: "HTI",
  hungary: "HUN",
  indonesia: "IDN",
  india: "IND",
  ireland: "IRL",
  "iran, islamic rep.": "IRN",
  iraq: "IRQ",
  iceland: "ISL",
  israel: "ISR",
  italy: "ITA",
  jamaica: "JAM",
  jordan: "JOR",
  japan: "JPN",
  kazakhstan: "KAZ",
  kenya: "KEN",
  "kyrgyz republic": "KGZ",
  kiribati: "KIR",
  "korea, rep.": "KOR",
  "lao pdr": "LAO",
  lebanon: "LBN",
  liberia: "LBR",
  "st. lucia": "LCA",
  "sri lanka": "LKA",
  lesotho: "LSO",
  lithuania: "LTU",
  luxembourg: "LUX",
  latvia: "LVA",
  morocco: "MAR",
  moldova: "MDA",
  madagascar: "MDG",
  maldives: "MDV",
  mexico: "MEX",
  "marshall islands": "MHL",
  "north macedonia": "MKD",
  mali: "MLI",
  malta: "MLT",
  myanmar: "MMR",
  montenegro: "MNE",
  mongolia: "MNG",
  mozambique: "MOZ",
  mauritania: "MRT",
  mauritius: "MUS",
  malawi: "MWI",
  malaysia: "MYS",
  namibia: "NAM",
  niger: "NER",
  nigeria: "NGA",
  nicaragua: "NIC",
  netherlands: "NLD",
  norway: "NOR",
  nepal: "NPL",
  nauru: "NRU",
  pakistan: "PAK",
  panama: "PAN",
  peru: "PER",
  philippines: "PHL",
  "papua new guinea": "PNG",
  poland: "POL",
  portugal: "PRT",
  paraguay: "PRY",
  "west bank and gaza": "PSE",
  romania: "ROU",
  "russian federation": "RUS",
  rwanda: "RWA",
  sudan: "SDN",
  senegal: "SEN",
  "solomon islands": "SLB",
  "sierra leone": "SLE",
  "el salvador": "SLV",
  somalia: "SOM",
  serbia: "SRB",
  "south sudan": "SSD",
  "sao tome and principe": "STP",
  "slovak republic": "SVK",
  slovenia: "SVN",
  sweden: "SWE",
  eswatini: "SWZ",
  seychelles: "SYC",
  "syrian arab republic": "SYR",
  chad: "TCD",
  togo: "TGO",
  thailand: "THA",
  tajikistan: "TJK",
  turkmenistan: "TKM",
  "timor-leste": "TLS",
  tonga: "TON",
  "trinidad and tobago": "TTO",
  tunisia: "TUN",
  turkiye: "TUR",
  tuvalu: "TUV",
  "taiwan, china": "TWN",
  tanzania: "TZA",
  uganda: "UGA",
  ukraine: "UKR",
  uruguay: "URY",
  "united states": "USA",
  uzbekistan: "UZB",
  vietnam: "VNM",
  vanuatu: "VUT",
  samoa: "WSM",
  kosovo: "XKX",
  "yemen, rep.": "YEM",
  "south africa": "ZAF",
  zambia: "ZMB",
  zimbabwe: "ZWE",
};
export default pairings;
